FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o proxy-app .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/proxy-app .

COPY config/ ./config/

EXPOSE 8080
CMD ["./proxy-app"]
